### ISSUE TITLE
Unable to install styledTables

### ISSUE THREAD

**Issue by liying2012** [R-package/styledtable#30]
I have a problem to install the styledTables package by using `devtools::install_github('R-package/styledTables', ref = "v0.2.0", build_opts = NULL)`. I got below error. Would anyone know how I could fix it? Thank you! 

```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref v0.2.0

  Did you spell the repo owner and repo name correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
 ```

**Comment by GregorDeCillia** [comment]
The package used to have a different name "styledTables" and therefore the repo was also named differently. Normally, github should be able to redirect requests using the old name to the new one but this does not seem to work here. @a-maldet changed the installation instructions of the README in https://github.com/R-package/styledtable/commit/e0c20faf23898c69be0fe34cdcea84d4f415337f. 

```r
devtools::install_github('R-package/styledtable', ref = "v0.2.0", build_opts = NULL)
```
